export const COMUNIDAD_DETAILS_REQUEST = 'COMUNIDAD_DETAILS_REQUEST'
export const COMUNIDAD_DETAILS_SUCCESS = 'COMUNIDAD_DETAILS_SUCCESS'
export const COMUNIDAD_DETAILS_FAIL = 'COMUNIDAD_DETAILS_FAIL'
export const COMUNIDAD_DETAILS_RESET = 'COMUNIDAD_DETAILS_RESET'

export const COMUNIDAD_UPDATE_PROFILE_REQUEST = 'COMUNIDAD_UPDATE_PROFILE_REQUEST'
export const COMUNIDAD_UPDATE_PROFILE_SUCCESS = 'COMUNIDAD_UPDATE_PROFILE_SUCCESS'
export const COMUNIDAD_UPDATE_PROFILE_FAIL = 'COMUNIDAD_UPDATE_PROFILE_FAIL'
export const COMUNIDAD_UPDATE_PROFILE_RESET = 'COMUNIDAD_UPDATE_PROFILE_RESET'
