export const CONSUMO_ESTADISTIC_LIST_REQUEST = 'CONSUMO_ESTADISTIC_LIST_REQUEST';
export const CONSUMO_ESTADISTIC_LIST_SUCCESS = 'CONSUMO_ESTADISTIC_LIST_SUCCESS';
export const CONSUMO_ESTADISTIC_LIST_FAIL = 'CONSUMO_ESTADISTIC_LIST_FAIL';
