// constants/cultivoConstants.js
export const CULTIVO_LIST_REQUEST = 'CULTIVO_LIST_REQUEST';
export const CULTIVO_LIST_SUCCESS = 'CULTIVO_LIST_SUCCESS';
export const CULTIVO_LIST_FAIL = 'CULTIVO_LIST_FAIL';

export const CULTIVO_DETAILS_REQUEST = 'CULTIVO_DETAILS_REQUEST';
export const CULTIVO_DETAILS_SUCCESS = 'CULTIVO_DETAILS_SUCCESS';
export const CULTIVO_DETAILS_FAIL = 'CULTIVO_DETAILS_FAIL';

export const FASE_CULTIVO_DETAILS_REQUEST = 'FASE_CULTIVO_DETAILS_REQUEST';
export const FASE_CULTIVO_DETAILS_SUCCESS = 'FASE_CULTIVO_DETAILS_SUCCESS';
export const FASE_CULTIVO_DETAILS_FAIL = 'FASE_CULTIVO_DETAILS_FAIL';
