// constants/documentConstants.js
export const DOCUMENTO_LIST_REQUEST = 'DOCUMENTO_LIST_REQUEST';
export const DOCUMENTO_LIST_SUCCESS = 'DOCUMENTO_LIST_SUCCESS';
export const DOCUMENTO_LIST_FAIL = 'DOCUMENTO_LIST_FAIL';

export const DOCUMENTO_CREATE_REQUEST = 'DOCUMENTO_CREATE_REQUEST';
export const DOCUMENTO_CREATE_SUCCESS = 'DOCUMENTO_CREATE_SUCCESS';
export const DOCUMENTO_CREATE_FAIL = 'DOCUMENTO_CREATE_FAIL';
export const DOCUMENTO_CREATE_RESET = 'DOCUMENTO_CREATE_RESET';

export const DOCUMENTO_DETAILS_REQUEST = 'DOCUMENTO_DETAILS_REQUEST';
export const DOCUMENTO_DETAILS_SUCCESS = 'DOCUMENTO_DETAILS_SUCCESS';
export const DOCUMENTO_DETAILS_FAIL = 'DOCUMENTO_DETAILS_FAIL';
