// constants/facturaConstants.js
export const FACTURA_LIST_REQUEST = 'FACTURA_LIST_REQUEST';
export const FACTURA_LIST_SUCCESS = 'FACTURA_LIST_SUCCESS';
export const FACTURA_LIST_FAIL = 'FACTURA_LIST_FAIL';

export const FACTURA_DETAILS_REQUEST = 'FACTURA_DETAILS_REQUEST';
export const FACTURA_DETAILS_SUCCESS = 'FACTURA_DETAILS_SUCCESS';
export const FACTURA_DETAILS_FAIL = 'FACTURA_DETAILS_FAIL';
