export const INCIDENCIA_LIST_REQUEST = 'INCIDENCIA_LIST_REQUEST';
export const INCIDENCIA_LIST_SUCCESS = 'INCIDENCIA_LIST_SUCCESS';
export const INCIDENCIA_LIST_FAIL = 'INCIDENCIA_LIST_FAIL';

export const INCIDENCIA_CREATE_REQUEST = 'INCIDENCIA_CREATE_REQUEST';
export const INCIDENCIA_CREATE_SUCCESS = 'INCIDENCIA_CREATE_SUCCESS';
export const INCIDENCIA_CREATE_FAIL = 'INCIDENCIA_CREATE_FAIL';
