export const PARCELA_CARACTERISTICAS_LIST_REQUEST = 'PARCELA_CARACTERISTICAS_LIST_REQUEST'
export const PARCELA_CARACTERISTICAS_LIST_SUCCESS = 'PARCELA_CARACTERISTICAS_LIST_SUCCESS'
export const PARCELA_CARACTERISTICAS_LIST_FAIL = 'PARCELA_CARACTERISTICAS_LIST_FAIL'

export const PARCELA_USOS_LIST_REQUEST = 'PARCELA_USOS_LIST_REQUEST'
export const PARCELA_USOS_LIST_SUCCESS = 'PARCELA_USOS_LIST_SUCCESS'
export const PARCELA_USOS_LIST_FAIL = 'PARCELA_USOS_LIST_FAIL'

export const PARCELA_CONTADORES_LIST_REQUEST = 'PARCELA_CONTADORES_LIST_REQUEST'
export const PARCELA_CONTADORES_LIST_SUCCESS = 'PARCELA_CONTADORES_LIST_SUCCESS'
export const PARCELA_CONTADORES_LIST_FAIL = 'PARCELA_CONTADORES_LIST_FAIL'

export const PARCELA_CONSUMOS_LIST_REQUEST = 'PARCELA_CONSUMOS_LIST_REQUEST'
export const PARCELA_CONSUMOS_LIST_SUCCESS = 'PARCELA_CONSUMOS_LIST_SUCCESS'
export const PARCELA_CONSUMOS_LIST_FAIL = 'PARCELA_CONSUMOS_LIST_FAIL'

export const PARCELA_DATOS_ADICIONALES_LIST_REQUEST = 'PARCELA_DATOS_ADICIONALES_LIST_REQUEST'
export const PARCELA_DATOS_ADICIONALES_LIST_SUCCESS = 'PARCELA_DATOS_ADICIONALES_LIST_SUCCESS'
export const PARCELA_DATOS_ADICIONALES_LIST_FAIL = 'PARCELA_DATOS_ADICIONALES_LIST_FAIL'

export const PARCELA_PAGOS_LIST_REQUEST = 'PARCELA_PAGOS_LIST_REQUEST'
export const PARCELA_PAGOS_LIST_SUCCESS = 'PARCELA_PAGOS_LIST_SUCCESS'
export const PARCELA_PAGOS_LIST_FAIL = 'PARCELA_PAGOS_LIST_FAIL'
