export const PETICION_LIST_REQUEST = 'PETICION_LIST_REQUEST';
export const PETICION_LIST_SUCCESS = 'PETICION_LIST_SUCCESS';
export const PETICION_LIST_FAIL = 'PETICION_LIST_FAIL';

export const PETICION_CREATE_REQUEST = 'PETICION_CREATE_REQUEST';
export const PETICION_CREATE_SUCCESS = 'PETICION_CREATE_SUCCESS';
export const PETICION_CREATE_FAIL = 'PETICION_CREATE_FAIL';
